globals:
    simulator-arguments:
        sampling-frequency: 4096
        duration: 1024
        start-time: 1577491218
    working-directory: .
    output-directory: output
    metadata-directory: metadata

orchestration:
    population:
        backend: FilePopulationLoader
        source-type: bbh
        n-samples: 1
        arguments:
            path: https://raw.githubusercontent.com/Leuven-Gravity-Institute/gwmock/main/examples/signal/bbh_population.csv
    signal:
        waveform-model: IMRPhenomXPHM
        minimum-frequency: 20
        detectors:
            - ET-Triangle-Sardinia
        output:
            output_directory: signal
            file_name:
                'E-{{ detectors }}_STRAIN_BBH-{{ start_time }}-{{ duration
                }}.gwf'
            arguments:
                channel: '{{ detectors }}:STRAIN'
    noise:
        arguments:
            psd_file: ET_10_full_cryo_psd
            seed: 42
            detectors:
                - E1_triangle_sardinia
        output:
            output_directory: noise
            file_name: et-noise-{{ counter }}.gwf
            arguments:
                channel_prefix: STRAIN
