"""Reference values for the end-to-end matrix: building them, and comparing against them.

Each matrix entry has a small JSON file under ``references/`` recording, per output file, the
content hash and a handful of summary statistics. The hash is what the tests assert on; the
statistics exist to make a failure *diagnosable* rather than merely red.

That split is the point. A bare hash tells you something changed and nothing about what, so
every failure becomes a bisect. With the statistics stored alongside, a mismatch reports which
files moved and by how much, and a one-part-in-10^15 drift from a library upgrade looks obviously
different from a waveform that shifted by samples or changed amplitude.

A mismatch is not automatically a bug. When a dependency bump changes the last bits of a
waveform, the right response is to look at the reported differences, decide the change is
harmless, and regenerate. When it changes a peak by a percent, it is not harmless. The stored
environment makes the first case quick to recognise -- it says which versions produced the
reference.

Regenerate with::

    GWMOCK_WRITE_E2E_REFERENCES=1 uv run pytest -m e2e --no-cov

Review the resulting diff before committing it. The references are small JSON in the repository
rather than an opaque archive precisely so that an update shows up as a reviewable change.

**Portability, and how far it has been established.** These hashes are known to reproduce
bit-for-bit between a local Linux/x86_64 machine and GitHub's ubuntu-latest runner on the same
Python -- measured, not assumed. Nothing is known about macOS, ARM, or a different BLAS.

So an exact match is only demanded when the run's :func:`fingerprint` matches the reference's.
Elsewhere the statistics are compared with :data:`STATISTIC_TOLERANCE` and the test skips, saying
which environments were involved.

Note what the fingerprint deliberately does *not* include: package versions. A dependency bump
changing a waveform is precisely what these references exist to surface, so putting versions in the
gate would silently downgrade the very comparison that is wanted. Versions are recorded, and
reported when a comparison fails, but they do not excuse a difference.
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Any

import numpy as np

from gwmock.cli.utils.hash import compute_content_hash

REFERENCES_DIR = Path(__file__).resolve().parent / "references"

#: Environment variable that switches the tests from comparing to writing.
WRITE_ENVIRONMENT_VARIABLE = "GWMOCK_WRITE_E2E_REFERENCES"

#: Packages whose versions are recorded with a reference. These are the ones whose output could
#: plausibly change a waveform or a noise realisation, so they are the first things to look at
#: when a comparison fails.
_RECORDED_PACKAGES = (
    "gwmock",
    "gwmock-signal",
    "gwmock-noise",
    "gwmock-pop",
    "numpy",
    "scipy",
    "lalsuite",
    "ripplegw",
    "jax",
)


#: Relative tolerance applied to ``peak`` and ``rms`` when the exact comparison is not available.
#:
#: **This number is not measured.** It is chosen to sit far below any physically meaningful change
#: -- a different waveform, a rescaled PSD, a lost taper all move these by percent or more -- and
#: far above the last-bit differences a different BLAS or libm produces for the same algorithm.
#: Nobody has measured how far apart two platforms actually land, so treat it as a bound on what
#: this check can detect rather than as a statement about numerical agreement.
STATISTIC_TOLERANCE = 1e-6


def writing_references() -> bool:
    """Return whether this run should write references instead of comparing against them.

    Raises:
        RuntimeError: If write mode is requested while ``CI`` is set. Regenerating references is a
            deliberate local act; a continuous-integration run that quietly rewrote them would
            overwrite the very thing it is supposed to be checking against and then report
            success.
    """
    requested = os.environ.get(WRITE_ENVIRONMENT_VARIABLE, "").strip().lower() in {"1", "true", "yes"}
    # Presence, not value: CI systems spell it CI=true, CI=1, and occasionally CI=. Failing closed
    # on any setting is right for a mode whose accidental use would overwrite the comparison.
    if requested and "CI" in os.environ:
        raise RuntimeError(
            f"{WRITE_ENVIRONMENT_VARIABLE} is set while CI is set. Reference values must not be "
            f"regenerated by a CI run: it would overwrite the comparison and then pass. Generate "
            f"them locally, review the diff, and commit it."
        )
    return requested


def fingerprint() -> dict[str, str]:
    """Return what distinguishes this numerical environment from another.

    Exact content hashes are only a fair comparison between runs on the *same* numerical stack.
    Package versions do not capture that: the same numpy and LAL built against a different BLAS,
    or on a different architecture, can produce different last bits for identical inputs. So the
    reference records a fingerprint, and the comparison uses it to decide whether an exact match
    is a reasonable thing to demand.
    """
    import platform
    import sys

    return {
        "system": platform.system(),
        "machine": platform.machine(),
        "python": ".".join(str(part) for part in sys.version_info[:2]),
    }


def _environment() -> dict[str, str]:
    """Return the installed versions of the packages that could change the data."""
    from importlib import metadata

    versions: dict[str, str] = {}
    for name in _RECORDED_PACKAGES:
        try:
            versions[name] = metadata.version(name)
        except metadata.PackageNotFoundError:
            versions[name] = "absent"
    return versions


def summarise(samples: np.ndarray) -> dict[str, Any]:
    """Return diagnostic statistics for one file's samples.

    Chosen so that the *kind* of a change is often readable from the numbers: ``peak`` and ``rms``
    move when amplitudes change, ``argmax`` when something shifts in time, ``nonzero`` when a
    signal appears or vanishes, and ``mean`` when signs invert.

    These triage a difference; they do not explain every one. A phase change that preserves the
    amplitude envelope, or a permutation of channels within a file, can leave all of them
    untouched -- the hash still catches such a change, but the report will say only that the
    recorded statistics are unchanged. That is a limit of the explanation, not of the detection.
    """
    finite = np.asarray(samples, dtype=float)
    return {
        "n": int(finite.size),
        "nonzero": int(np.count_nonzero(finite)),
        "peak": float(np.max(np.abs(finite))) if finite.size else 0.0,
        "rms": float(np.sqrt(np.mean(finite**2))) if finite.size else 0.0,
        "argmax": int(np.argmax(np.abs(finite))) if finite.size else 0,
        # Signed, so an inversion shows up. `peak` and `rms` are both magnitudes and would not
        # move at all if every sample changed sign.
        "mean": float(np.mean(finite)) if finite.size else 0.0,
    }


def build_reference(label: str, working_directory: Path, files: list[Path]) -> dict[str, Any]:
    """Return a reference document describing what a run produced.

    Args:
        label: The matrix entry's label.
        working_directory: The run directory, used to make paths relative.
        files: The data files the run wrote.

    Returns:
        A JSON-serialisable reference document.
    """
    from .runner import samples

    outputs: dict[str, Any] = {}
    for path in sorted(files):
        outputs[str(path.relative_to(working_directory))] = {
            "content_hash": compute_content_hash(path),
            **summarise(samples(path)),
        }
    return {
        "label": label,
        "environment": _environment(),
        "fingerprint": fingerprint(),
        "outputs": outputs,
    }


def reference_path(label: str) -> Path:
    """Return the file storing *label*'s reference, with slashes flattened for a filename."""
    return REFERENCES_DIR / f"{label.replace('/', '__')}.json"


def write_reference(document: dict[str, Any]) -> Path:
    """Write *document* and return where it went."""
    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    path = reference_path(document["label"])
    path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def load_reference(label: str) -> dict[str, Any] | None:
    """Return *label*'s stored reference, or ``None`` if there is not one yet."""
    path = reference_path(label)
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def statistic_differences(stored: dict[str, Any], produced: dict[str, Any]) -> list[str]:
    """Return the statistics that differ beyond what floating-point drift explains.

    Used instead of the hash when the two runs are not on the same numerical stack, where an exact
    match is not a fair thing to require. Integer statistics -- sample count, occupancy, the peak's
    position -- must match exactly, because no amount of last-bit drift moves them. The float
    magnitudes are compared with :data:`STATISTIC_TOLERANCE`.
    """
    differences: list[str] = []
    for name in sorted(set(stored) & set(produced)):
        before, after = stored[name], produced[name]
        for key in ("n", "nonzero", "argmax"):
            if before.get(key) != after.get(key):
                differences.append(f"{name}: {key} {before.get(key)!r} -> {after.get(key)!r}")
        for key in ("peak", "rms", "mean"):
            old, new = float(before.get(key, 0.0)), float(after.get(key, 0.0))
            # A NaN makes every comparison below false, so it would be read as "no difference".
            # Non-finite values are the difference.
            if not (math.isfinite(old) and math.isfinite(new)):
                differences.append(f"{name}: {key} {old!r} -> {new!r} (not finite)")
                continue
            scale = max(abs(old), abs(new))
            if scale and abs(new - old) / scale > STATISTIC_TOLERANCE:
                differences.append(f"{name}: {key} {old!r} -> {new!r} (relative {abs(new - old) / scale:.3e})")
    return differences


def describe_difference(stored: dict[str, Any], produced: dict[str, Any]) -> str:
    """Return a human-readable account of how a run differs from its reference.

    Written to answer the question a failure actually raises -- *is this harmless?* -- so it
    reports the statistics side by side with a relative change, and the environment differences,
    rather than only saying that two hashes are unequal.
    """
    lines: list[str] = []

    stored_outputs, produced_outputs = stored.get("outputs", {}), produced.get("outputs", {})
    missing = sorted(set(stored_outputs) - set(produced_outputs))
    extra = sorted(set(produced_outputs) - set(stored_outputs))
    if missing:
        lines.append(f"  files in the reference but not produced: {missing}")
    if extra:
        lines.append(f"  files produced but not in the reference: {extra}")

    for name in sorted(set(stored_outputs) & set(produced_outputs)):
        before, after = stored_outputs[name], produced_outputs[name]
        if before.get("content_hash") == after.get("content_hash"):
            continue
        lines.append(f"  {name}:")
        for key in ("n", "nonzero", "argmax", "peak", "rms", "mean"):
            old, new = before.get(key), after.get(key)
            if old == new:
                continue
            if isinstance(old, float) and isinstance(new, float) and old != 0.0:
                relative = abs(new - old) / abs(old)
                lines.append(f"    {key}: {old!r} -> {new!r}  (relative change {relative:.3e})")
            else:
                lines.append(f"    {key}: {old!r} -> {new!r}")
        if all(before.get(key) == after.get(key) for key in ("n", "nonzero", "argmax", "peak", "rms", "mean")):
            lines.append("    every recorded statistic is unchanged; the difference is below them")

    changed_environment = {
        name: (stored.get("environment", {}).get(name), produced.get("environment", {}).get(name))
        for name in sorted(set(stored.get("environment", {})) | set(produced.get("environment", {})))
        if stored.get("environment", {}).get(name) != produced.get("environment", {}).get(name)
    }
    if changed_environment:
        lines.append("  versions that differ from when the reference was written:")
        lines.extend(f"    {name}: {old} -> {new}" for name, (old, new) in changed_environment.items())
    else:
        lines.append("  no recorded package version changed, so a dependency bump does not explain this")

    return "\n".join(lines) if lines else "  no differences found"
