globals:
    simulator-arguments:
        sampling-frequency: 4096
        duration: 4096
        total-duration: 1 day
        start-time: 1000000540
    working-directory: .
    output-directory: output
    metadata-directory: metadata

orchestration:
    population:
        backend: FilePopulationLoader
        source-type: bbh
        arguments:
            path: 'https://sandbox.zenodo.org/records/514722/files/mdc1_bbh.h5'
    signal:
        waveform-model: IMRPhenomXPHM
        minimum-frequency: 10
        earth-rotation: true
        detectors:
            - ET-2L-Aligned
        output:
            output_directory: signal
            file_name:
                'E-{{ detectors }}_STRAIN_BBH-{{ start_time }}-{{ duration
                }}.hdf5'
            arguments:
                channel: '{{ detectors }}:STRAIN'
