globals:
    simulator-arguments:
        sampling-frequency: 4096
        duration: 4096
        total-duration: 1 day
        start-time: 1577491218
    working-directory: .
    output-directory: output
    metadata-directory: metadata

orchestration:
    noise:
        arguments:
            seed: 42
            detectors:
                - E1_2L_misaligned_sardinia
            glitches:
                - kind: gengli_blip
                  rate: 0.016666667 # 1 glitch per minute (1/60 Hz)
                  amplitude_distribution: # no amplitude scaling (multiply by 1.0)
                      distribution: lognormal
                      mean: 1.0
                      std: 0.0
                  population_file: https://sandbox.zenodo.org/records/514722/files/blip_glitch_population_E1.hdf5
                  psd_file: ET_15_full_cryo_psd
                  low_frequency_cutoff: 5.0
        output:
            output_directory: glitch
            file_name:
                'E-{{ detectors }}_STRAIN_GLITCH-{{ start_time }}-{{ duration
                }}.hdf5'
            arguments:
                channel: '{{ detectors }}:STRAIN'
